# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dashboard.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61shboard.proto\x12\tdashboard\"\xce\x01\n\rTrainingBatch\x12\x0e\n\x06images\x18\x01 \x03(\x0c\x12\x13\n\x0bpred_labels\x18\x02 \x03(\t\x12\x13\n\x0btrue_labels\x18\x03 \x03(\t\x12\x0c\n\x04loss\x18\x04 \x01(\x02\x12\x0c\n\x04step\x18\x05 \x01(\x03\x12\r\n\x05\x65poch\x18\x06 \x01(\x05\x12\x12\n\nbatch_size\x18\x07 \x01(\x05\x12\x19\n\x11sent_timestamp_ms\x18\x08 \x01(\x03\x12\x13\n\x0bimage_width\x18\t \x01(\x05\x12\x14\n\x0cimage_height\x18\n \x01(\x05\"\"\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"=\n\x0bPingRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x1b\n\x13\x63lient_timestamp_ms\x18\x02 \x01(\x03\"y\n\x0cPingResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x1b\n\x13server_timestamp_ms\x18\x03 \x01(\x03\x12\x19\n\x11\x66rames_per_second\x18\x04 \x01(\x05\x12\x12\n\nqueue_size\x18\x05 \x01(\x05\x32\x8d\x01\n\x10\x44\x61shboardService\x12@\n\x12StreamTrainingData\x12\x18.dashboard.TrainingBatch\x1a\x0e.dashboard.Ack(\x01\x12\x37\n\x04Ping\x12\x16.dashboard.PingRequest\x1a\x17.dashboard.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dashboard_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRAININGBATCH']._serialized_start=31
  _globals['_TRAININGBATCH']._serialized_end=237
  _globals['_ACK']._serialized_start=239
  _globals['_ACK']._serialized_end=273
  _globals['_PINGREQUEST']._serialized_start=275
  _globals['_PINGREQUEST']._serialized_end=336
  _globals['_PINGRESPONSE']._serialized_start=338
  _globals['_PINGRESPONSE']._serialized_end=459
  _globals['_DASHBOARDSERVICE']._serialized_start=462
  _globals['_DASHBOARDSERVICE']._serialized_end=603
# @@protoc_insertion_point(module_scope)
