# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from services.proto import dashboard_pb2 as dashboard__pb2


class DashboardServiceStub(object):
    """===============================
    Service Definition
    ===============================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTrainingData = channel.stream_unary(
                '/dashboard.DashboardService/StreamTrainingData',
                request_serializer=dashboard__pb2.TrainingBatch.SerializeToString,
                response_deserializer=dashboard__pb2.Ack.FromString,
                )
        self.Ping = channel.unary_unary(
                '/dashboard.DashboardService/Ping',
                request_serializer=dashboard__pb2.PingRequest.SerializeToString,
                response_deserializer=dashboard__pb2.PingResponse.FromString,
                )


class DashboardServiceServicer(object):
    """===============================
    Service Definition
    ===============================

    """

    def StreamTrainingData(self, request_iterator, context):
        """Training app sends a stream of TrainingBatch messages during training.
        Dashboard consumes them and returns a simple Ack when training is done.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Optional health check / status RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DashboardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTrainingData': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTrainingData,
                    request_deserializer=dashboard__pb2.TrainingBatch.FromString,
                    response_serializer=dashboard__pb2.Ack.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=dashboard__pb2.PingRequest.FromString,
                    response_serializer=dashboard__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dashboard.DashboardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DashboardService(object):
    """===============================
    Service Definition
    ===============================

    """

    @staticmethod
    def StreamTrainingData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/dashboard.DashboardService/StreamTrainingData',
            dashboard__pb2.TrainingBatch.SerializeToString,
            dashboard__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dashboard.DashboardService/Ping',
            dashboard__pb2.PingRequest.SerializeToString,
            dashboard__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
